---
- hosts: webservers
  become: yes
  tasks:
          - name: updating repos
            yum:
                    name: "*"
                    state: latest
          - name: Install Tomcat
            yum:
                    name: tomcat-webapps.noarch
          - name: Start Tomcat
            service:
                    name: tomcat
                    state: started
          - name: deploy war file
            copy:
                    src: sample.war
                    dest: /usr/share/tomcat/webapps
          - name: ReStart Tomcat
            service:
                    name: tomcat
                    state: restarted
...
